name: valet_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  video_player: ^2.7.0
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Inter-Italic
      fonts:
        - asset: fonts/Inter-Italic-VariableFont_opsz,wght.ttf
    - family: Fenix
      fonts:
        - asset: fonts/Fenix-Regular.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter-VariableFont_opsz,wght.ttf
